### ISSUE TITLE
dropping "national

### ISSUE THREAD

**Issue by chrissoria** [chrissoria/BICS_Political_Polarization#1]
DF/Merge_to_BICS.ipynb

Question: Do we delete all values city != "national" OR do we weight and keep all values for city.

BICS_ZIP_FEATURES['city'].value_counts()

BICS_ZIP_FEATURES = BICS_ZIP_FEATURES[BICS_ZIP_FEATURES['city'] == "National"]

**Comment by dfeehan** [comment]
Based on our Slack, I think this is resolved - but lmk if that is not right!
