### ISSUE TITLE
Weights when subsetting waves

### ISSUE THREAD

**Issue by chrissoria** [chrissoria/BICS_Political_Polarization#2]
Does it still make sense to use these same weights if I'm subsetting the data by wave? Or, is weight_pooled only designed to be used when lumping all the waves together?

example: 

# Model for Wave 2 (June 18-24, '20)
contacts_R_v_D_w2 <- glm.nb(num_cc_nonhh ~  `rate_prev_6/14/20` + State_Government_Response_Index_11192020 + COUNTY_RUCC_2013 + male + educ_group + resp_yob + r_working + Income_Category + r_race + political_party, data = subset(bics_zip_features, wave == 2, weights = weight_pooled))

#model for Wave 3 (September 12-20, '20)
contacts_R_v_D_w3 <- glm.nb(num_cc_nonhh ~ `rate_prev_9/9/20` +State_Government_Response_Index_11192020 + COUNTY_RUCC_2013 + male + educ_group + resp_yob + r_working + Income_Category + r_race + political_party, data = subset(bics_zip_features, wave == 3))

**Comment by dfeehan** [comment]
Good question! It makes sense to use those weights when subsetting by wave. (The weights are calculated separately for each wave)
